on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: step1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --all
          git branch --list -a
          next_branch=$(git branch --list -r '*.*_next' | xargs)
          echo "next_branch=$next_branch" >> $GITHUB_ENV
      - run: echo ${{ env.next_branch }}
