on: 
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
        - major
        - minor
        - patch
        default: patch
        required: true
env:
  next_branch: 3.2_next
  main_branch: 3.2_main
  preview_branch: 3.2_preview
  
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.next_branch }}
      - uses: actions/setup-node@v3
      - run: |
            npm --no-git-tag-version version ${{ inputs.release_type }}
            new_version=$(node -p "require('./package.json').version")
            git config user.name 'GitHub Action'
            git config user.email '<>'
            git checkout -fB "release/${new_version}"
            branch_exists=$(git branch -r | grep "release/${new_version}" || echo "")
            echo $branch_exists
            if [ -z $branch_exists ]; then
              echo "foo"
              git pull origin "release/${new_version}"
              new_version=$(node -p "require('./package.json').version")
            else
              echo "nope"
            fi
            npm --no-git-tag-version --preid='rc' version prerelease
            git add .
            git commit -m "Prepare $(node -p "require('./package.json').version")"
            git push --set-upstream origin "release/${new_version}"
            gh pr view "release/${new_version}"
            gh pr create --title "Prepare ${new_version}" --body '' -B "${{ env.preview_branch }}"
