on: 
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
        - major
        - minor
        - patch
        default: patch
        required: true
        
env:
  next_branch: 3.2_next
  preview_branch: 3.2_preview
  
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.next_branch }}
      - uses: actions/setup-node@v3
      - run: |
            npm --no-git-tag-version version ${{ inputs.release_type }}
            new_version=$(node -p "require('./package.json').version")
            git config user.name 'GitHub Action'
            git config user.email '<>'
            git checkout -fB "release/${new_version}"
            git pull origin "release/${new_version}" || echo "Branch doesn't exist"
            npm --no-git-tag-version --preid='rc' version prerelease
            rc_version=$(node -p "require('./package.json').version")
            git add .
            git commit -m "Prepare ${rc_version}"
            git push --set-upstream origin "release/${new_version}"
            gh pr create --title "Prepare ${rc_version}" --body '' -B "${{ env.preview_branch }}" || gh pr edit --title "Prepare ${rc_version}"
