on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: step1
        run: |
          git pull --all
          echo "next_branch=$(echo $(echo $(git branch -lr 'origin/*.*_next' | sed -n 's/.*origin\/\([[:digit:]].[[:digit:]]\)_next/\1/p')))" >> $GITHUB_ENV
          echo "release_branch=$(git branch -lr 'release/*.*')" >> $GITHUB_ENV
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git switch "${{ env.next_branch }}_next"
            gh repo view marvjohnson/composit-action-workflow --branch 3.2_next
