on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: step1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull --all
          git branch -lr
          echo "next_branch=$(echo $(git branch -lr 'origin/*.*_next' | grep -E '^[[:blank:]]{2}(origin/.\.._next))$')"
      - run: echo ${{ env.next_branch }}
