on: 
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
        - major
        - minor
        - patch
        default: patch
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: |
          git pull --all
          echo "next_branch=$(echo $(echo $(git branch -lr 'origin/*.*_next' | sed -n 's/.*origin\/\([[:digit:]].[[:digit:]]\)_next/\1/p')))" >> $GITHUB_ENV
      - run: |
            git switch "${{ env.next_branch }}_next"
            npm --no-git-tag-version version ${{ inputs.release_type }}
            echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config user.name 'GitHub Action'
            git config user.email '<>'
            git checkout -B 'release/${{ env.new_version }}'
            npm --no-git-tag-version --preid='rc' version prerelease
            git add .
            git commit -m "Prepare $(node -p "require('./package.json').version")"
            git push origin 'release/${{ env.new_version }}'
            gh pr create --title "Prepare $(node -p "require('./package.json').version")" --body ''
            
