on: workflow_dispatch

env:
  TEST: Hello
  PAT: ${{ secrets.pat }}

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        if: ${{ env.pat != '' }}
        run: echo "$PAT $TEST"
      - shell: bash
        if: ${{ env.pat == '' }}
        run: echo "no pat! $TEST"
