on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
        - major
        - minor
        - patch
        default: patch
        required: true

jobs:
  prepare_release:
    uses: marvjohnson/composit-action/.github/workflows/action.yml@main
    with:
      release_type: ${{ inputs.release_type }}
