on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        options:
        - major
        - minor
        - patch
        required: true

jobs:
  prepare_release:
    uses: marvjohnson/composit-action/.github/workflows/action.yml@main
    with:
      version_type: ${{ inputs.version_type }}
