on:
  workflow_dispatch:
    inputs:
      version:
        type: string
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: marvjohnson/composit-action@v1
        env:
          VERSION: ${{ inputs.version }}
        with:
          version: $VERSION
