on: workflow_dispatch

env:
  TEST: Hello
  PAT: ${{ secrets.pat }}

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        if: ${{ env.PAT != '' }}
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \ 
            -H "Authorization: token $PAT" \
            -d '{"ref":"topic-branch","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}' \
            https://api.github.com/repos/marvjohnson/test-action/actions/workflows/test.yml/dispatches
      - shell: bash
        if: ${{ env.PAT == '' }}
        run: echo "no pat! $TEST"
