on:
  workflow_dispatch:
    inputs:
      repo:
        type: choice
        options:
        - test-action
        - test-action2

env:
  PAT: ${{ secrets.pat }}
  REPO: ${{ inputs.repo }}

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        if: ${{ env.PAT != '' }}
        run: |
          curl https://api.github.com/repos/marvjohnson/$REPO/actions/workflows/test.yml/dispatches -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $PAT" -d '{"ref":"main"}'
      - shell: bash
        if: ${{ env.PAT == '' }}
        run: echo "no pat! $TEST"
