on:
  workflow_dispatch:
    inputs:
      test:
        description: 'some input'
        type: choice
        options:
        - thing1
        - thing2

jobs:
  foo:
    runs-on: ubuntu-latest
    name: A job to test composit actions
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: MarvJohnson/composit-action@v1
        with:
          foo: 'Hello World!'
      - run: echo ${{ steps.foo.outputs.bar }}
        shell: bash
