on: workflow_dispatch
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          PAT: ${{ secrets.pat }}
        if: ${{ env.pat != '' }}
        run: echo "$PAT"
      - shell: bash
        env:
          PAT: ${{ secrets.pat }}
        if: ${{ env.pat == '' }}
        run: echo "no pat!"
