on:
  workflow_dispatch:
    inputs:
      new_version:
        type: string
        required: true
jobs:
  prepare_release:
    uses: marvjohnson/composit-action/.github/workflows/action.yml@main
    with:
      NEW_VERSION: ${{ inputs.new_version }}
