on:
  workflow_dispatch:
    inputs:
      new_version:
        type: string
        required: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  prepare_release:
    uses: marvjohnson/composit-action/.github/workflows/action.yml@main
    with:
      new_version: ${{ inputs.new_version }}
