on:
  workflow_dispatch:
    inputs:
      test:
        description: 'some input'
        type: choice
        options:
        - thing1
        - thing2

jobs:
  foo:
    uses: MarvJohnson/test-action/tree/main/.github/workflows/test.yml@main
