on:
  workflow_dispatch:
    inputs:
      new_version:
        type: choice
        options:
        - major
        - minor
        - patch
        required: true

jobs:
  prepare_release:
    uses: marvjohnson/composit-action/.github/workflows/action.yml@main
    with:
      new_version: ${{ inputs.new_version }}
